### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/pyuntl#18]

**Comment by ldko** [comment]
We'll want to make a new branch for Python 3 and get tests to pass in Python 3.6 and 3.7. We can drop support for Python 2 in this branch.

@madhulika95b I am assigning this to you, since I haven't gotten there yet, and it is a dependency of aubreylib-which you have already done work to convert. Thanks!

**Comment by madhulika95b** [comment]
python 3 support is added to py3 branch.
